Step 1: Import Libraries and Create Dataset

In [2]:
import pandas as pd
import random

random.seed(42)

regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)

print(df.head(10))
print(f"\nDataset shape: {df.shape}")

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

# **Task 1: Basic Grouping and Aggregations**

step 1 Total Sales per Region

In [3]:
region_sales = df.groupby('region')['sales_amount'].sum().reset_index()
region_sales

  region  sales_amount
0   East      95189.81
1  North     135181.16
2  South     158977.36
3   West     109383.07

step 2 Sort Regions by Sales

In [4]:
region_sales_sorted = region_sales.sort_values(by='sales_amount', ascending=False)
region_sales_sorted

  region  sales_amount
2  South     158977.36
1  North     135181.16
3   West     109383.07
0   East      95189.81

step 3 Count Transactions per Category

In [5]:
category_transactions = df.groupby('category')['transaction_id'].count().reset_index()
category_transactions

        category  transaction_id
0          Books              39
1       Clothing              42
2    Electronics              45
3  Home & Garden              43
4         Sports              31

step 4 Average Sales per Salesperson

In [6]:
salesperson_avg = df.groupby('salesperson')['sales_amount'].mean().reset_index()
salesperson_avg

  salesperson  sales_amount
0       Alice   1998.432273
1         Bob   2554.919063
2       Carol   2454.368571
3       David   2743.036444
4        Emma   2493.457273
5       Frank   2464.135750

# **Task 2: Multi-Column Grouping**

step 1 Sales by Region and Category

In [7]:
region_category_sales = df.groupby(['region', 'category'])['sales_amount'].sum().reset_index()
region_category_sales

   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22

step 2 Salesperson Performance Metrics

In [8]:
salesperson_stats = df.groupby('salesperson')['sales_amount'].agg(['sum','mean','count']).reset_index()
salesperson_stats

  salesperson        sum         mean  count
0       Alice   43965.51  1998.432273     22
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
3       David  123436.64  2743.036444     45
4        Emma   82284.09  2493.457273     33
5       Frank   98565.43  2464.135750     40

step 3 Sort by Total Sales

In [9]:
salesperson_stats_sorted = salesperson_stats.sort_values(by='sum', ascending=False)
salesperson_stats_sorted

  salesperson        sum         mean  count
3       David  123436.64  2743.036444     45
5       Frank   98565.43  2464.135750     40
4        Emma   82284.09  2493.457273     33
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
0       Alice   43965.51  1998.432273     22

step 4 Category with Maximum Revenue

In [10]:
category_sales = df.groupby('category')['sales_amount'].sum()
top_category = category_sales.idxmax()
print("Category with highest revenue:", top_category)

Category with highest revenue: Electronics

# **Task 3: Custom Aggregation**

step 1 Create Custom Function

In [12]:
def sales_range(x):
    return x.max() - x.min()

step 2 Apply Aggregations by Region

In [13]:
region_analysis = df.groupby('region')['sales_amount'].agg(['sum','mean','min','max',sales_range]).reset_index()
region_analysis

  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

# **final report**

In [14]:
final_report = df.groupby('region').agg({
    'sales_amount': ['sum','mean'],
    'customer_id': 'count'
}).reset_index()

final_report

  region sales_amount              customer_id
                  sum         mean       count
0   East     95189.81  2213.716512          43
1  North    135181.16  2413.949286          56
2  South    158977.36  2789.076491          57
3   West    109383.07  2485.978864          44